- hosts: localhost
  become: true
  become_user: root

  tasks:
  # install MS Arc connected machines agent
    - name: Download the Connected Machine Agent on Linux servers
      become: true
      get_url:
        url: https://aka.ms/azcmagent
        dest: ~/install_linux_azcmagent.sh
        mode: '700'
      #when: (ansible_system == 'Linux') and (azcmagent_lnx_downloaded.stat.exists == false)
    
    - name: Install the Connected Machine Agent on Linux servers
      become: true
      shell: bash ~/install_linux_azcmagent.sh

    - name: Connect the Connected Machine Agent on Linux servers to Azure Arc
      become: true
      shell: azcmagent connect --resource-name "{{ az_name }}-{{ gcp_vmid.stdout }}" --service-principal-id "{{ az_sp }}" --service-principal-secret "{{ az_sp_scrt }}" --resource-group "{{ az_rg }}" --tenant-id "{{ az_tenant }}" --location "{{ az_loc }}" --subscription-id "{{ az_sub }}"
