# Apply common configuration to all hosts
- hosts: localhost
  become: true
  become_user: root

  tasks:
    - name: update packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        use_backend: dnf