---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: localhost
  become: yes
  become_user: root

  vars:
    azure:
      service_principal_id: "'{{ lookup('ansible.builtin.env', 'HOME') }}'"
      service_principal_secret: "'{{ lookup('ansible.builtin.env', 'HOME') }}'"
      resource_group: "'{{ lookup('ansible.builtin.env', 'HOME') }}'"
      tenant_id: "'{{ lookup('ansible.builtin.env', 'HOME') }}'"
      subscription_id: "'{{ lookup('ansible.builtin.env', 'HOME') }}'"
      location: "'{{ lookup('ansible.builtin.env', 'HOME') }}'"

  pre_tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
        
    - name: update base os and software
      ansible.builtin.apt:
        upgrade: dist
  
  tasks:
    - name: Connect the Connected Machine Agent on Linux servers to Azure Arc
      become: yes
      shell: azcmagent connect --service-principal-id "{{ azure.service_principal_id }}" --service-principal-secret "{{ azure.service_principal_secret }}" --resource-group "{{ azure.resource_group }}" --tenant-id "{{ azure.tenant_id }}" --location "{{ azure.location }}" --subscription-id "{{ azure.subscription_id }}"
