---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: localhost
  become: yes
  become_user: root
  
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
        
    - name: update base os and software
      ansible.builtin.apt:
        upgrade: dist
        
    #- name: connect arc connected machines agent
    - name: clone wazuh ansible role
      git:
        repo: https://github.com/wazuh/wazuh-ansible.git
        dest: /etc/ansible/roles/
        clone: yes
        update: yes

    #- name: install portainer

