---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: localhost
  become: true
  become_user: root

  #pre_tasks:
    #- name: update apt cache
      #ansible.builtin.apt:
        #update_cache: yes
        
    #- name: update base os and software
      #ansible.builtin.apt:
        #upgrade: dist
    
  tasks:
    - name: Disconnect the Connected Machine Agent and delete Linux servers to Azure Arc
      become: true
      shell: azcmagent disconnect -i "{{ az_sp }}" -p "{{ az_sp_scrt }}" --resource-group "{{ az_rg }}" --user-tenant-id "{{ az_tenant }}"

    - name: Connect the Connected Machine Agent on Linux servers to Azure Arc
      become: true
      shell: azcmagent connect --resource-name "{{ ansible_fqdn }}" --service-principal-id "{{ az_sp }}" --service-principal-secret "{{ az_sp_scrt }}" --resource-group "{{ az_rg }}" --tenant-id "{{ az_tenant }}" --location "{{ az_loc }}" --subscription-id "{{ az_sub }}"
