---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: localhost
  become: yes
  become_user: root

  pre_tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
        
    - name: update base os and software
      ansible.builtin.apt:
        upgrade: dist
  
  tasks:
    - name: Connect the Connected Machine Agent on Linux servers to Azure Arc
      become: yes
      shell: azcmagent connect --service-principal-id "{{ lookup('env','azure.service_principal_id' }}" --service-principal-secret "{{ lookup('env','azure.service_principal_secret' }}" --resource-group "{{ lookup('env','azure.resource_group' }}" --tenant-id "{{ lookup('env','azure.tenant_id' }}" --location "{{ lookup('env','azure.location' }}" --subscription-id "{{ lookup('env','azure.subscription_id' }}"
