---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: all
  become: yes
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
        
    - name: update base os and software
      ansible.builtin.apt:
        upgrade: dist
        
    #- name: connect arc connected machines agent

    - name: get & install wazuh agent
      apt_key:
        url: "{{ UrlWazuhAgent }}"
        state: present
    
    - name: configure apt wazuh repo
      apt_repository:
        repo: "{{ RepoWazuhAgent }}"
        state: present
        filename: "{{ RepoDest }}"
    
    - name: update apt
        apt:
          update_cache: true
          
    - name: 
      apt:
        name: wazuh-agent={{ WazuhVersion }}-1
        state: present
    template:
      src: "{{ ConfigWazuh }}"
      dest: "{{ ConfigDestWazuh }}"
      mode: "{{ ConfigPermission }}"
    notify: WazuhAgentServiceStartEnableAndReload

    

    #- name: install portainer

