---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: localhost
  become: yes
  become_user: root

  pre_tasks:
    - name: clone wazuh ansible role
      git:
        repo: https://github.com/wazuh/wazuh-ansible.git
        dest: /etc/ansible/roles/
        clone: yes
        update: yes
  
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: yes
        
    - name: update base os and software
      ansible.builtin.apt:
        upgrade: dist

- hosts: localhost
  become: yes
  become_user: root
  roles:
    - ../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: "{{ lookup('env','WAZUH_SERVER') }}"
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'https'
        api_user: wazuh
        max_retries: 5
        retry_interval: 5
