---
# This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: localhost
  become: true
  become_user: root

  vars:
    azure:
      service_principal_id: "'{{ lookup('ansible.builtin.env', 'service_principal_id') }}'"
      service_principal_secret: "'{{ lookup('ansible.builtin.env', 'service_principal_secret') }}'"
      resource_group: "'{{ lookup('ansible.builtin.env', 'resource_group') }}'"
      tenant_id: "'{{ lookup('ansible.builtin.env', 'tenant_id') }}'"
      subscription_id: "'{{ lookup('ansible.builtin.env', 'subscription_id') }}'"
      location: "{{ lookup('ansible.builtin.env', 'location') | quote }}"

  #pre_tasks:
    #- name: update apt cache
      #ansible.builtin.apt:
        #update_cache: yes
        
    #- name: update base os and software
      #ansible.builtin.apt:
        #upgrade: dist
  
  tasks:
    - debug:
      msg: "{{ lookup('ansible.builtin.env', 'location') | quote }}"
    - name: Connect the Connected Machine Agent on Linux servers to Azure Arc
      become: true
      shell: azcmagent connect --service-principal-id "{{ azure.service_principal_id }}" --service-principal-secret "{{ azure.service_principal_secret }}" --resource-group "{{ azure.resource_group }}" --tenant-id "{{ azure.tenant_id }}" --location "{{ azure.location }}" --subscription-id "{{ azure.subscription_id }}"
