---
- hosts: localhost
  become: yes
  become_user: root

  tasks:
    - name: clone wazuh ansible role
      git:
        repo: https://github.com/wazuh/wazuh-ansible.git
        dest: /etc/ansible/roles/
        clone: yes
        update: yes

