---
- hosts: localhost
  become: yes
  become_user: root
  roles:
    #- ../roles/wazuh/ansible-wazuh-agent
    - /etc/ansible/roles/wazuh-ansible/roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: "{{ wazuh_srv }}"
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'https'
        api_user: wazuh
        max_retries: 5
        retry_interval: 5