---
- hosts: localhost
  become: yes
  become_user: root

  pre_tasks:
    - name: get latest wazuh release version
      ansible.builtin.uri:
        url: https://api.github.com/repos/wazuh/wazuh-ansible/releases/latest
        body_format: json
        return_content: true
      register: wazuh_version

  tasks:
    - name: clone wazuh ansible role
      ansible.builtin.git:
        repo: https://github.com/wazuh/wazuh-ansible.git
        dest: /etc/ansible/roles/wazuh-ansible/
        clone: yes
        update: yes
        single_branch: true
        version: "{{ wazuh_version.json.tag_name }}"

- hosts: localhost
  become: yes
  become_user: root
  roles:
    #- ../roles/wazuh/ansible-wazuh-agent
    - /etc/ansible/roles/wazuh-ansible/roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: "{{ wazuh_srv }}"
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'https'
        api_user: wazuh
        max_retries: 5
        retry_interval: 5