---
- hosts: localhost
  become: yes
  become_user: root

  tasks:
    - name: clone wazuh ansible role
      ansible.builtin.git:
        repo: https://github.com/wazuh/wazuh-ansible.git
        dest: /etc/ansible/roles/wazuh-ansible/
        clone: yes
        update: yes
        single_branch: true
        version: master

